config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    match '/scrape/:type', to: 'posts#scrape', via: :get, on: :collection, as: :scrape
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_crawler.rb
class PostCrawler < Kimurai::Base
  @name = 'post_crawler'
  @engine = :selenium_chrome

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response = browser.current_response
    response.css('list-unstyled.news-feed-items.index-load-more-container').each do |post|
      browser.visit(url)
      puts browser.current_response.to_json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def scrape
    url = ''
    case params[:type]
    when 'says'
      url = 'https://says.com/my'
    when 'therakyat'
    else
    end
    response = PostCrawler.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :link, :published_time, :category, :group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_area :link %>
  </div>

  <div>
    <%= form.label :published_time, style: "display: block" %>
    <%= form.text_area :published_time %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_area :category %>
  </div>

  <div>
    <%= form.label :group, style: "display: block" %>
    <%= form.text_field :group %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= post.link %>
  </p>

  <p>
    <strong>Published time:</strong>
    <%= post.published_time %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= post.category %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= post.group %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.slim
h1 Posts

- @posts.each do |post|
  = render post

= link_to "Scrape SAYS post", scrape_posts_path('says')
= link_to "Scrape The Rakyat post", scrape_posts_path('therakyat')
= link_to "Scrape Berita Harian post", scrape_posts_path('beritaharian')

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/scrape.slim
= notice 
= alert 

= link_to 'Back', root_path

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>